---
kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: git

steps:
  - name: build
    image: docker
    privileged: true
    environment: 
      TOKEN:
        from_secret: gitea
    commands:
      - dockerd &
      - docker login -u kieran -p $TOKEN git.v0l.io
      - docker buildx create --name mybuilder --bootstrap --use
      - docker buildx build -t git.v0l.io/kieran/void-cat:latest --platform linux/amd64 --push .
      - kill $(cat /var/run/docker.pid)