version: "3.9"
services:
  web:
    build: .
    ports:
      - "8001:80"
    volumes:
      - "./VoidCat/appsettings.compose.json:/app/appsettings.json:ro"
    depends_on:
      - postgres
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6079:6379"
  postgres:
    image: "postgres:14.1"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=void"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  clamav:
    image: "clamav/clamav"
    ports:
      - "3320:3310"