services:
  redis:
    image: "redis:alpine"
    ports:
      - "6079:6379"
  postgres:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=void"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  clamav:
    image: "clamav/clamav"
    ports:
      - "3320:3310"