name: build
on:
  push:
    branches: [ v4-re ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v1
        with:
          username: voidic
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build the Docker image
        run: docker buildx build -t ghcr.io/v0l/void.cat/app:latest -t voidic/void.cat:latest --platform linux/amd64 --push .
      - name: Build the NoSPA Docker image
        run: docker buildx build -t ghcr.io/v0l/void.cat/api:latest -t voidic/void.cat:api-latest -f nospa.dockerfile --platform linux/amd64 --push .
